### ISSUE TITLE
findEncodings() function should return ALSO the reverse complements

### ISSUE THREAD

**Issue by ignaciordc** [weka511/bioinformatics#103]
DEFINITION: We say that a DNA string _Pattern_ encodes an amino acid string _Peptide_ if the RNA string transcribed from either Pattern or its reverse complement Pattern translates into _Peptide_.

The 'encodes()' function applies that rule when checking if a pattern encodes a peptide.
However, I think the function _findEncodings_() is not returning all the patterns in the passed DNA

Try that with
_findEncodings_('ATGGCCATGGCCCCCAGAACTGAGATCAATAGTACCCGTATTAACGGGTGA', 'MA')

The reason? Since the function should return all possible ways of writing the _pattern_, (in the previous example, 'MA' and 'AM'), we should consider all possible ways of writing the peptide, which is a **cycle**.

It the peptide is 'ABC', it should check 'ABC', 'BCA', 'CAB', 'CBA', 'BAC' and 'ACB'

**Comment by weka511** [comment]
This isn't in accordance with my reading of the [problem description](http://rosalind.info/problems/ba4b/). I don't see where cycles come into the description.

**Comment by ignaciordc** [comment]
Hi,

You are right and the description <http://rosalind.info/problems/ba4b/> is
what it is.
 It was my fault in a simpler implementation of revc.

Another little glitch, without effects: pay attention to the limit used in
your code to define candidates:

>>> candidates = [text[i:i+3*len(peptide)] for i in range(*len(text)-3)*]

for the candidates at the end of the sequence do not have the right length.
Has no effect, but should be  *len(text) - 3*len(peptide) + 1* )

Cheers,
    Ignacio

**Comment by ignaciordc** [comment]
Simon,

I am using Python 2.7 and, therefore, this one might not occur in Python
3...
I am talking again about Rosalind.py.
In that file, "score()" is defined as a global routine.
In your routine "trim()" there is a call to "score" that says


 peptides_with_scores=[ (score(peptide,spectrum,spectrum_generator),peptide)\
                                        for peptide in leaderBoard ]

Python 2 tries to look for score in its local vars, and not finding it,
looks for a variable in the global list, not finding it, and so I get


     UnboundLocalError: local variable 'score' referenced before assignment


An easy fix or that is to include score in the list of optional
arguments of the function, similarly to what you have done in other
functions:

        def trim(leaderBoard, spectrum,n,spectrum_generator=linearSpectrum,
*score=score*):

Hope this helps,
   Ignacio
