### ISSUE TITLE
longest_path in align.py is not working

### ISSUE THREAD

**Issue by ignaciordc** [weka511/bioinformatics#105]
There is an important issue in this routine, which makes it fail.
The error resides in _calculate_distances()_.
The line
                _new_s=max(s[b],s[a]+(weights[(a,b)] if (a,b) in weights else **0**))_
should be
                  _new_s=max(s[b],s[a]+(weights[(a,b)] if (a,b) in weights else -**maxint**))_
otherwise, a is considered a predecessor of b and everything after that goes wrong.

I have checked that fix with a much larger test set and it works.

NOTE: I am using _maxint_, while the current code uses _float_info_ in the initialization of the variable _s_.
Since we are working with integers, _maxint_ makes more sense to me.

Another, minor one: _topological_order()_ is destroying the parameter passed, _graph_.
This routine is calling **del graph[a]** till it gets _len(graph)==0_. 
That is, when we exit the routine we have an empty _graph={}_.
Depending on when this routine is called, the bug might affect the code following that call.
Instead, _topological_order_() should make a copy of the dict passed, and use it, and delete elements of this copy when needed, leaving the original _graph_ untouched.

**Comment by weka511** [comment]
See [this discussion](https://stackoverflow.com/questions/13795758/what-is-sys-maxint-in-python-3) of maxint for my choice of float_info

**Comment by weka511** [comment]
Issue #114 was the same issue, so I am closing
